### ISSUE TITLE
sdb failing on purely userland ZFS debugging with "LookupError: could not find 'struct task_struct *'"

### ISSUE THREAD

**Issue by rincebrain** [delphix/sdb#283] opened 2021-11-23 17:12 UTC
** Expected Behavior**
A useful interactive debugging session should have existed

** Actual Behavior**
On trying to run any useful command, you get errors like:
```
$ sdb cmd/ztest/.libs/ztest  core.ztest.593006.ubuntu20.1637654931
sdb> thread
sdb encountered an internal error due to a bug. Here's the
information you need to file the bug:
----------------------------------------------------------
Target Info:
        ProgramFlags.0
        Platform(<Architecture.X86_64: 1>, <PlatformFlags.IS_LITTLE_ENDIAN|IS_64_BIT: 3>)

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/internal/repl.py", line 107, in eval_cmd
    for obj in invoke(self.target, [], input_):
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/pipeline.py", line 153, in invoke
    yield from execute_pipeline(first_input, pipeline)
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/pipeline.py", line 84, in execute_pipeline
    yield from massage_input_and_call(pipeline[-1], this_input)
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/pipeline.py", line 47, in massage_input_and_call
    expected_type = target.get_type(cmd.input_type)
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/target.py", line 55, in get_type
    return prog.type(type_name)
LookupError: could not find 'struct task_struct *'
----------------------------------------------------------
Link: https://github.com/delphix/sdb/issues/new
```

**Steps To Reproduce the Problem**
I don't know - I ensued linux-image-$(uname -r)-dbgsym libdw1 libdw-dev drgn and sdb were installed (the latter two with python3 setup.py install, since VM), then tried running common commands and death ensued.

It seems like it can't figure out how to read the stubbed out kernel bits in ztest - if I manually hand it -s module/os/linux/spl/spl-taskq.o, it graduates to:
```
sdb> threads
sdb encountered an internal error due to a bug. Here's the
information you need to file the bug:
----------------------------------------------------------
Target Info:
        ProgramFlags.0
        Platform(<Architecture.X86_64: 1>, <PlatformFlags.IS_LITTLE_ENDIAN|IS_64_BIT: 3>)

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/internal/repl.py", line 107, in eval_cmd
    for obj in invoke(self.target, [], input_):
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/pipeline.py", line 153, in invoke
    yield from execute_pipeline(first_input, pipeline)
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/pipeline.py", line 84, in execute_pipeline
    yield from massage_input_and_call(pipeline[-1], this_input)
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/pipeline.py", line 67, in massage_input_and_call
    yield from cmd.call(objs)
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/command.py", line 328, in call
    yield from self.__invalid_memory_objects_check(
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/command.py", line 290, in __invalid_memory_objects_check
    for obj in objs:
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/command.py", line 775, in _call
    self.pretty_print(self.caller(objs))
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/commands/threads.py", line 91, in pretty_print
    for obj in objs:
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/command.py", line 736, in caller
    yield from self.no_input()
  File "/usr/local/lib/python3.8/dist-packages/sdb-0.1.0-py3.8.egg/sdb/commands/threads.py", line 97, in no_input
    yield from for_each_task(sdb.get_prog())
  File "/usr/local/lib/python3.8/dist-packages/drgn-0.0.14+71.gd18be05-py3.8-linux-x86_64.egg/drgn/helpers/linux/pid.py", line 72, in for_each_task
    for pid in for_each_pid(prog_or_ns):
  File "/usr/local/lib/python3.8/dist-packages/drgn-0.0.14+71.gd18be05-py3.8-linux-x86_64.egg/drgn/helpers/linux/pid.py", line 42, in for_each_pid
    ns = prog_or_ns["init_pid_ns"].address_of_()
KeyError: 'init_pid_ns'
----------------------------------------------------------
Link: https://github.com/delphix/sdb/issues/new
```

Same error if you just hand it the whole built ZFS tree checkout...

**Screenshots**
N/A

**Version**
Ubuntu 20.04 LTS up to date
ZFS git slightly edited from openzfs/zfs@ded851b2e
drgn v0.0.14-71-gd18be05
sdb 3e6c69a

**Additional Context**
Not sure what else I'd include.

**Comment by pcd1193182** [comment] 2023-03-13 21:07
The fundamental issue here is that the `stacks` and `threads` commands of SDB assume that we're operating in the kernel.  They declare their input types to be `struct task_struct *`, which is the kernel structure you get back from `for_each_task` in drgn. If you operate directly on global variables and the like, things should mostly just work.

Resolving this issue will probably require having different definitions of certain commands based on the runtime (kernel or userland).

**Comment by pcd1193182** [comment] 2023-03-13 22:31
Closing as a dupe of #303, since that project is intended to solve this (and other) issaues.

**Closed by pcd1193182** 2023-03-13 22:31 UTC
