### ISSUE TITLE
stacks command fails 

### ISSUE THREAD

**Issue by cneira** [delphix/sdb#138] opened 2020-01-22 15:13 UTC
I just installed sdb using  cfde1b63c0bb300116191ccf2b4f2d71abaf9765 and the stack command is broken.

```bash
sdb> stacks
TASK_STRUCT        STATE             COUNT
==========================================
sdb encountered an internal error due to a bug. Here's the
information you need to file the bug:
----------------------------------------------------------
Target Info:
	ProgramFlags.IS_LIVE|IS_LINUX_KERNEL
	Platform(<Architecture.X86_64: 1>, <PlatformFlags.IS_LITTLE_ENDIAN|IS_64_BIT: 3>)

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 85, in eval_cmd
    for obj in invoke(self.target, [], input_):
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/pipeline.py", line 165, in invoke
    yield from execute_pipeline(first_input, pipeline)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/pipeline.py", line 83, in execute_pipeline
    yield from massage_input_and_call(pipeline[-1], this_input)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/pipeline.py", line 43, in massage_input_and_call
    yield from cmd.call(objs)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/command.py", line 233, in call
    result = self._call(objs)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/commands/stacks.py", line 298, in _call
    for task in for_each_task(sdb.get_prog()):
  File "/usr/local/lib/python3.6/dist-packages/drgn-0.0.1-py3.6-linux-x86_64.egg/drgn/helpers/linux/pid.py", line 102, in for_each_task
    PIDTYPE_PID = prog["PIDTYPE_PID"].value_()
KeyError: 'PIDTYPE_PID'
```
I compiled drgn  b2c1a613ec9b7925a2987afbc9c28dfc0139bb9b have not tested with an older version yet.

**Comment by sdimitro** [comment] 2020-01-22 16:08
Hi @cneira !

Thank you for using sdb and submitting a bug!
Reading the stack trace that you provided I can tell the following:
[1] sdb calls into the drgn API with a call to `for_each_task()`
``File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/commands/stacks.py", line 298, in _call
    for task in for_each_task(sdb.get_prog()):`
```
[2]  Then drgn tries to find the value of the `PIDTYPE_PID` contant that is part of `enum pid_type`
```
File "/usr/local/lib/python3.6/dist-packages/drgn-0.0.1-py3.6-linux-x86_64.egg/drgn/helpers/linux/pid.py", line 102, in for_each_task
    PIDTYPE_PID = prog["PIDTYPE_PID"].value_()
KeyError: 'PIDTYPE_PID'
```

There must be something weird happening with the target Linux kernel that you're trying to introspect as it looks like that enum is missing (which is weird because that enum has been the same since v2.6 of the Linux kernel).

Could you provide the following information:
[1] What is the command that you use to invoke sdb? `sdb -k`, `sdb [vmlinux] [crash dump]` ?
[2] Do you get any errors or warnings once sdb or drgn starts?
[2] Do you by any chance compile your one kernel with your own config?

Thanks again for filling an issue and looking forward to hear on the above info.

**Comment by cneira** [comment] 2020-01-22 16:19
@sdimitro  
Thanks for the quick response!.
sdb looks really good, I really miss using mdb at work so this seems like an awesome alternative in Linux.

[1]  _What is the command that you use to invoke sdb?_

      sdb and sdb -k both show the same error.

[2] _Do you get any errors or warnings once sdb or drgn starts ?_

     Yes, I'm sorry to not include them in the bug report

```bash
cneira@boldo:~/Opensource/drgn$ sudo sdb 
sdb: could not get debugging information for:
kernel (could not find vmlinux for 5.3.0-26-generic)
/lib/modules/5.3.0-26-generic/kernel/drivers/misc/mei/mei-me.ko (libdwfl error: No DWARF information found)
/lib/modules/5.3.0-26-generic/kernel/drivers/input/input-leds.ko (libdwfl error: No DWARF information found)
/lib/modules/5.3.0-26-generic/kernel/net/ipv6/netfilter/ip6table_filter.ko (libdwfl error: No DWARF information found)
/lib/modules/5.3.0-26-generic/kernel/drivers/net/wireless/ralink/rt2x00/rt2x00lib.ko (libdwfl error: No DWARF information found)
... 132 more
sdb> 
cneira@boldo:~/Opensource/drgn$ sudo drgn
could not get debugging information for:
kernel (could not find vmlinux for 5.3.0-26-generic)
/lib/modules/5.3.0-26-generic/kernel/drivers/misc/mei/mei-me.ko (libdwfl error: No DWARF information found)
/lib/modules/5.3.0-26-generic/kernel/drivers/input/input-leds.ko (libdwfl error: No DWARF information found)
/lib/modules/5.3.0-26-generic/kernel/net/ipv6/netfilter/ip6table_filter.ko (libdwfl error: No DWARF information found)
/lib/modules/5.3.0-26-generic/kernel/drivers/net/wireless/ralink/rt2x00/rt2x00lib.ko (libdwfl error: No DWARF information found)
... 132 more
drgn 0.0.1 (using Python 3.6.9, without libkdumpfile)
For help, type help(drgn).
>>> import drgn
>>> from drgn import NULL, Object, cast, container_of, execscript, reinterpret, sizeof
>>> from drgn.helpers.linux import *
>>> 
```
```bash
cneira@boldo:~/Opensource/drgn$ sudo sdb -k
sdb: could not get debugging information for:
kernel (could not find vmlinux for 5.3.0-26-generic)
/lib/modules/5.3.0-26-generic/kernel/drivers/input/input-leds.ko (libdwfl error: No DWARF information found)
/lib/modules/5.3.0-26-generic/kernel/drivers/misc/mei/mei-me.ko (libdwfl error: No DWARF information found)
/lib/modules/5.3.0-26-generic/kernel/drivers/net/wireless/ralink/rt2x00/rt2x00lib.ko (libdwfl error: No DWARF information found)
/lib/modules/5.3.0-26-generic/kernel/fs/jfs/jfs.ko (libdwfl error: No DWARF information found)
... 132 more
sdb> stacks
TASK_STRUCT        STATE             COUNT
==========================================
sdb encountered an internal error due to a bug. Here's the
information you need to file the bug:
----------------------------------------------------------
Target Info:
	ProgramFlags.IS_LIVE|IS_LINUX_KERNEL
	Platform(<Architecture.X86_64: 1>, <PlatformFlags.IS_LITTLE_ENDIAN|IS_64_BIT: 3>)

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 85, in eval_cmd
    for obj in invoke(self.target, [], input_):
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/pipeline.py", line 165, in invoke
    yield from execute_pipeline(first_input, pipeline)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/pipeline.py", line 83, in execute_pipeline
    yield from massage_input_and_call(pipeline[-1], this_input)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/pipeline.py", line 43, in massage_input_and_call
    yield from cmd.call(objs)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/command.py", line 233, in call
    result = self._call(objs)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/commands/stacks.py", line 298, in _call
    for task in for_each_task(sdb.get_prog()):
  File "/usr/local/lib/python3.6/dist-packages/drgn-0.0.1-py3.6-linux-x86_64.egg/drgn/helpers/linux/pid.py", line 102, in for_each_task
    PIDTYPE_PID = prog["PIDTYPE_PID"].value_()
KeyError: 'PIDTYPE_PID'
----------------------------------------------------------
Link: https://github.com/delphix/sdb/issues/new
sdb> 
cneira@boldo:~/Opensource/drgn$ sudo sdb 
sdb: could not get debugging information for:
kernel (could not find vmlinux for 5.3.0-26-generic)
/lib/modules/5.3.0-26-generic/kernel/drivers/input/input-leds.ko (libdwfl error: No DWARF information found)
/lib/modules/5.3.0-26-generic/kernel/drivers/misc/mei/mei-me.ko (libdwfl error: No DWARF information found)
/lib/modules/5.3.0-26-generic/kernel/net/ipv6/netfilter/ip6table_filter.ko (libdwfl error: No DWARF information found)
/lib/modules/5.3.0-26-generic/kernel/drivers/net/wireless/ralink/rt2x00/rt2x00lib.ko (libdwfl error: No DWARF information found)
... 132 more
sdb> stacks
TASK_STRUCT        STATE             COUNT
==========================================
sdb encountered an internal error due to a bug. Here's the
information you need to file the bug:
----------------------------------------------------------
Target Info:
	ProgramFlags.IS_LIVE|IS_LINUX_KERNEL
	Platform(<Architecture.X86_64: 1>, <PlatformFlags.IS_LITTLE_ENDIAN|IS_64_BIT: 3>)

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/internal/repl.py", line 85, in eval_cmd
    for obj in invoke(self.target, [], input_):
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/pipeline.py", line 165, in invoke
    yield from execute_pipeline(first_input, pipeline)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/pipeline.py", line 83, in execute_pipeline
    yield from massage_input_and_call(pipeline[-1], this_input)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/pipeline.py", line 43, in massage_input_and_call
    yield from cmd.call(objs)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/command.py", line 233, in call
    result = self._call(objs)
  File "/usr/local/lib/python3.6/dist-packages/sdb-0.1.0-py3.6.egg/sdb/commands/stacks.py", line 298, in _call
    for task in for_each_task(sdb.get_prog()):
  File "/usr/local/lib/python3.6/dist-packages/drgn-0.0.1-py3.6-linux-x86_64.egg/drgn/helpers/linux/pid.py", line 102, in for_each_task
    PIDTYPE_PID = prog["PIDTYPE_PID"].value_()
KeyError: 'PIDTYPE_PID'
----------------------------------------------------------
```
 [3] _Do you by any chance compile your one kernel with your own config?_

      No, I'm running a stock kernel. 

```bash
Linux boldo 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by sdimitro** [comment] 2020-01-22 16:38
Glad to hear! Yeah, the whole idea of sdb is to provide a more mdb-like experience in Linux.

Ok so I see two problems here - one caused by your environment and one on sdb's side in terms of error handling:

[Problem 1] It seems like drgn (and thus sdb) cannot find the debug information of your kernel and its kernel modules on the system, that's why you get all the `libdwfl error: No DWARF information found` errors during startup. This is because of one of the following two reasons: (I) The debug symbols are not installed on your system (II) The debug symbols are installed but at some custom location that is not the default. If you are in case (I) you need to install the debug information yourself on that machine (Some pointers here: https://wiki.ubuntu.com/Debug%20Symbol%20Packages and here: https://wiki.ubuntu.com/Kernel/Systemtap - see "Where do I get debug symbols for kernel X" in the second link). If you are in case (II) you need to specify the location of your debug info to `sdb` or `drgn` with the `-s` option when you invoke them. For example: `sdb -s <custom path>/vmlinux-4.15.0-1057-aws`.

[Problem 2] Certain commands like `stacks` require debug information (DWARF data) to work in sdb (since they rely on DWARF-dependent drgn calls. It is a bit annoying that the user has to download those separately, although that is understandable as DWARF takes a lot of space (in Illumos almost all binaries and the kernel would come with CTF info which is very light so it always included). I don't think sdb and drgn can fix that any of this soon (e.g. relying on something that is always available - like BTF in most 5.0+ distribution kernels). BUT we could at least do a better job of conveying the problem to the user.

Let me know if you were able to make any progress in your environment with problem [1]. Once you are setup correctly I will close this bug and open another one for better error messages in sdb.

**Comment by cneira** [comment] 2020-01-23 12:16
@sdimitro,
Thank you very much for your help, now it works!.
```bash
cneira@boldo:~/Opensource/drgn$ sudo apt-get install linux-image-$(uname -r)-dbgsym
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  grub-pc-bin libido3-0.1-0 libllvm8
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  linux-image-unsigned-5.3.0-26-generic-dbgsym
The following NEW packages will be installed:
  linux-image-5.3.0-26-generic-dbgsym linux-image-unsigned-5.3.0-26-generic-dbgsym
0 upgraded, 2 newly installed, 0 to remove and 23 not upgraded.
Need to get 899 MB of archives.
After this operation, 6.270 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ddebs.ubuntu.com bionic-updates/main amd64 linux-image-unsigned-5.3.0-26-generic-dbgsym amd64 5.3.0-26.28~18.04.1 [899 MB]
Get:2 http://ddebs.ubuntu.com bionic-updates/main amd64 linux-image-5.3.0-26-generic-dbgsym amd64 5.3.0-26.28~18.04.1 [6.028 B]                                                                       
Fetched 899 MB in 4min 8s (3.631 kB/s)                                                                                                                                                                
Selecting previously unselected package linux-image-unsigned-5.3.0-26-generic-dbgsym.
(Reading database ... 201561 files and directories currently installed.)
Preparing to unpack .../linux-image-unsigned-5.3.0-26-generic-dbgsym_5.3.0-26.28~18.04.1_amd64.ddeb ...
Unpacking linux-image-unsigned-5.3.0-26-generic-dbgsym (5.3.0-26.28~18.04.1) ...
Selecting previously unselected package linux-image-5.3.0-26-generic-dbgsym.
Preparing to unpack .../linux-image-5.3.0-26-generic-dbgsym_5.3.0-26.28~18.04.1_amd64.ddeb ...
Unpacking linux-image-5.3.0-26-generic-dbgsym (5.3.0-26.28~18.04.1) ...
Setting up linux-image-unsigned-5.3.0-26-generic-dbgsym (5.3.0-26.28~18.04.1) ...
Setting up linux-image-5.3.0-26-generic-dbgsym (5.3.0-26.28~18.04.1) ...
cneira@boldo:~/Opensource/drgn$ sdb
sdb: [Errno 13] Permission denied: '/proc/kcore'
cneira@boldo:~/Opensource/drgn$ sudo sdb
sdb: could not get debugging information for:
/lib/modules/5.3.0-26-generic/extra/nvidia-modeset.ko (libdwfl error: No DWARF information found)
/lib/modules/5.3.0-26-generic/extra/nvidia.ko (libdwfl error: No DWARF information found)
/lib/modules/5.3.0-26-generic/extra/nvidia-drm.ko (libdwfl error: No DWARF information found)
/lib/modules/5.3.0-26-generic/extra/nvidia-uvm.ko (libdwfl error: No DWARF information found)
sdb> stacks
TASK_STRUCT        STATE             COUNT
==========================================
0xffff9360da75de00 INTERRUPTIBLE       288
                  __schedule+0x2a8
                  schedule+0x33
                  futex_wait_queue_me+0xc4
                  futex_wait+0x10f
                  do_futex+0x364
                  __x64_sys_futex+0x13f
                  do_syscall_64+0x5a
                  entry_SYSCALL_64+0x7c

0xffff936717032f00 INTERRUPTIBLE       174
                  __schedule+0x2a8
                  schedule+0x33
                  schedule_hrtimeout_range_clock+0x181
                  schedule_hrtimeout_range+0x13
                  poll_schedule_timeout.constprop.11+0x46
                  do_sys_poll+0x3d7
                  do_restart_poll+0x49
                  __ia32_sys_restart_syscall+0x25
                  do_syscall_64+0x5a
                  entry_SYSCALL_64+0x7c

0xffff936715a60000 INTERRUPTIBLE       155
                  __schedule+0x2a8
                  schedule+0x33
                  schedule_hrtimeout_range_clock+0x181
                  schedule_hrtimeout_range+0x13
                  poll_schedule_timeout.constprop.11+0x46
                  do_sys_poll+0x3d7
                  __x64_sys_poll+0x3b
                  do_syscall_64+0x5a
                  entry_SYSCALL_64+0x7c

0xffff936718770000 INTERRUPTIBLE        39
                  __schedule+0x2a8
                  schedule+0x33
                  schedule_hrtimeout_range_clock+0xb9
                  schedule_hrtimeout_range+0x13
                  poll_schedule_timeout.constprop.11+0x46
                  do_sys_poll+0x3d7
                  __x64_sys_poll+0xa5
                  do_syscall_64+0x5a
                  entry_SYSCALL_64+0x7c
...
```

**Comment by sdimitro** [comment] 2020-01-23 17:13
@cneira - That's great to hear! I'll close this bug and open a new for more user-friendly warnings.
Feel free to ping me again for any other issues you hit

**Closed by sdimitro** 2020-01-23 17:13 UTC
